/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package possystem.ui;

import possystem.ui.billing.BillingWindow;
import possystem.ui.dailyRecords.DailyRecordWindow;

/**
 *
 * @author dushantha.eranga
 */
public class WindowSelector extends javax.swing.JFrame
{

    /**
     * Creates new form WindowSelector
     */
    public WindowSelector()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnBillinWindow = new javax.swing.JButton();
        btnDailyRecordWindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBillinWindow.setText("Billing Window");
        btnBillinWindow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBillinWindowActionPerformed(evt);
            }
        });

        btnDailyRecordWindow.setText("Daily Record Window");
        btnDailyRecordWindow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDailyRecordWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDailyRecordWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBillinWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBillinWindow)
                .addGap(18, 18, 18)
                .addComponent(btnDailyRecordWindow)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBillinWindowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBillinWindowActionPerformed
    {//GEN-HEADEREND:event_btnBillinWindowActionPerformed
        // TODO add your handling code here:
        BillingWindow billingWindow = new BillingWindow();
        billingWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBillinWindowActionPerformed

    private void btnDailyRecordWindowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDailyRecordWindowActionPerformed
    {//GEN-HEADEREND:event_btnDailyRecordWindowActionPerformed
        // TODO add your handling code here:
        DailyRecordWindow dailyRecordWindow = new DailyRecordWindow();
        dailyRecordWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDailyRecordWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(WindowSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(WindowSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(WindowSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(WindowSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new WindowSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillinWindow;
    private javax.swing.JButton btnDailyRecordWindow;
    // End of variables declaration//GEN-END:variables
}
