/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package possystem.ui.common;

import javax.swing.table.TableColumn;

/**
 *
 * @author dushantha.eranga
 */
public class ItemTable extends javax.swing.JPanel
{

    /**
     * Creates new form TablePanel
     */
    public ItemTable()
    {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        customTable1 = new possystem.ui.util.CustomTable();

        customTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private possystem.ui.util.CustomTable customTable1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void initializeItemTable()
    {
        ItemTableModel tableModel = new ItemTableModel();
        customTable1.setModel(tableModel);
        
        //((JLabel) customTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        
        for (int i = 0; i < customTable1.getColumnCount(); i++)
        {
            TableColumn column = customTable1.getColumnModel().getColumn(i);
            if(i == 1)
            {
                column.setPreferredWidth(150);
            }
            //column.setMaxWidth(140);
            //column.setMinWidth(40);
            //column.setCellRenderer(cellRendererCenter);
        }
        
        //customTable1.getTableHeader().setReorderingAllowed(false);
        //customTable1.setRowSelectionAllowed(true);        
        //customTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
    }
    
    private ItemTableModel getTableModel()
    {
        return ((ItemTableModel) customTable1.getModel());
    }
    
    /**
     * Update table
     */
    public void updateTable()
    {
        getTableModel().updateTableModel();
    }
}

